services:
  vigil:
    container_name: vigil
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      - debug_mode=...
      - bot_group_id=...
      - bot_acces_token=...
      - cahche_host=...
      - cahche_post=...
      - cahche_db=...
      - db_dialect=...
      - db_user=...
      - db_password=...
      - db_hostname=...
    ports:
      - "25565:8080"