services:
  bot:
    container_name: bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - debug_mode=...
      - bot_group_id=...
      - bot_acces_token=...
      - cahche_post=...
      - cahche_db=...
      - db_dialect=...
      - db_user=...
      - db_password=...
      - db_hostname=...
    volumes:
      - ./db:/app/db
      - ./config:/app/config
  
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
      - ./config:/app/config
    depends_on:
      - bot