services:
  bot:
    container_name: bot
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - debug_mode=...
      - bot_group_id=...
      - bot_acces_token=...
      - cahche_host=...
      - cahche_post=...
      - cahche_db=...
      - db_dialect=...
      - db_user=...
      - db_password=...
      - db_hostname=...