CREATE USER ... WITH PASSWORD '...';
CREATE DATABASE ...;
GRANT ALL PRIVILEGES ON DATABASE ... TO ...;

CREATE USER ... WITH PASSWORD '...';
CREATE DATABASE ...;
GRANT ALL PRIVILEGES ON DATABASE ... TO ...;