CREATE USER vigil WITH PASSWORD '...';
CREATE DATABASE bot;
GRANT ALL PRIVILEGES ON DATABASE bot TO vigil;

CREATE USER nginx WITH PASSWORD '...';
CREATE DATABASE npm;
GRANT ALL PRIVILEGES ON DATABASE npm TO nginx;