[tool.poetry]
package-mode = false
name = "web"
authors = ["Oidaho <oidaho.main@yandex.ru>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
